### ISSUE TITLE
Street Name search no longer working

### ISSUE THREAD

**Issue by chriswhong** [NYCPlanning/labs-streets#241] opened 2018-09-18 17:10 UTC
Try searching for "Flatbush" or "Hylan", we used to show street name matches in search, and highlight them on the map.

Street results no longer appear in search.

**Comment by trbmcginnis** [comment] 2018-10-11 14:48
It seems like searching for alterations is not working either, if you start to type in "cp2..." it says no results immediately

**Comment by rtblair** [comment] 2021-07-02 19:01
Unable to reproduce. Closing.
<img width="1468" alt="Screen Shot 2021-07-02 at 3 00 29 PM" src="https://user-images.githubusercontent.com/662963/124318200-482c7980-db46-11eb-861d-c299754c6c7f.png">

**Closed by rtblair** 2021-07-02 19:01 UTC
